"""add games table

Revision ID: 0ea8407b71ce
Revises: 8aaa911eafd8
Create Date: 2026-03-30 10:47:46.535437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea8407b71ce'
down_revision = '8aaa911eafd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('max_scenes', sa.Integer(), nullable=False),
    sa.Column('max_sprites', sa.Integer(), nullable=False),
    sa.Column('max_scripts_per_scene', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_owner_id'))

    op.drop_table('games')
    # ### end Alembic commands ###
