"""added tiers to xp logs

Revision ID: 1cc22bc92c41
Revises: 809e99d6d7ed
Create Date: 2026-04-07 13:40:10.897180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc22bc92c41'
down_revision = '809e99d6d7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_xp_logs_tier'), ['tier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_logs_tier'))
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
