"""Add default_scene_id to games

Revision ID: 5009793de140
Revises: 1cc22bc92c41
Create Date: 2026-04-09 09:31:04.885131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5009793de140'
down_revision = '1cc22bc92c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_scene_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_games_default_scene_id', 'scenes', ['default_scene_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_games_default_scene_id', type_='foreignkey')
        batch_op.drop_column('default_scene_id')

    # ### end Alembic commands ###
