"""Created other models

Revision ID: 809e99d6d7ed
Revises: 0ea8407b71ce
Create Date: 2026-03-30 11:27:20.351715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809e99d6d7ed'
down_revision = '0ea8407b71ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('unlocked_by_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avatar_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avatar_items_category'), ['category'], unique=False)

    op.create_table('daily_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checked_in_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checkins_user_id'), ['user_id'], unique=False)

    op.create_table('user_avatar_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['avatar_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.create_table('game_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    op.create_table('game_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_purchases_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_purchases_resource'), ['resource'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_purchases_user_id'), ['user_id'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_game_id'), ['game_id'], unique=False)

    op.create_table('sprites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('draft_image_path', sa.String(length=512), nullable=True),
    sa.Column('published_image_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sprites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprites_game_id'), ['game_id'], unique=False)

    op.create_table('xp_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xp_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_logs_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_logs_user_id'), ['user_id'], unique=False)

    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('published_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scripts_scene_id'), ['scene_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scripts_scene_id'))

    op.drop_table('scripts')
    with op.batch_alter_table('xp_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_xp_logs_game_id'))

    op.drop_table('xp_logs')
    with op.batch_alter_table('sprites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprites_game_id'))

    op.drop_table('sprites')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_game_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('game_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_purchases_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_purchases_resource'))
        batch_op.drop_index(batch_op.f('ix_game_purchases_game_id'))

    op.drop_table('game_purchases')
    op.drop_table('game_likes')
    op.drop_table('user_avatar_items')
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_checkins_user_id'))

    op.drop_table('daily_checkins')
    with op.batch_alter_table('avatar_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatar_items_category'))

    op.drop_table('avatar_items')
    # ### end Alembic commands ###
