"""daily checkins unique per user per day

Revision ID: e857c52f0471
Revises: 5009793de140
Create Date: 2026-04-10 12:17:16.445887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e857c52f0471'
down_revision = '5009793de140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_daily_checkins_user_date', ['user_id', 'checked_in_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_constraint('uq_daily_checkins_user_date', type_='unique')

    # ### end Alembic commands ###
